---
title: "Presentation"
author: "Group"
date: "4/20/2022"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(knitr)
library(magrittr)
library(tidyr)

full_data <-  read.csv("Dataset/cleaned_data.csv")
data <- full_data %>%
  drop_na
final_model <- (
    log(PriceinUK) ~
      log(Subtitle) +
      poly(Acceleration, 2, raw = T) + 
      poly(TopSpeed, 2, raw = T) +
      log(Efficiency) +
      NumberofSeats
) %>%
  lm(data)
```

## Introduction

* Description

* Research Question:

    **Which characteristics of Electric Vehicles have a significant impact on their price?**

## Data Description

## Process
<!-- I need to fill out this when I finish this part of the paper. -->

## Final Model
$$
\begin{align*}
\ln \texttt{PriceinUK} &= \beta_0 \\
&+ \beta_1 \ln \texttt{Subtitle} \\
&+ \beta_2 \texttt{Acceleration} \\
&+ \beta_3 \texttt{Acceleration}^2 \\
&+ \beta_4 \texttt{TopSpeed} \\
&+ \beta_5 \texttt{TopSpeed}^2 \\
&+ \beta_6 \ln \texttt{Efficiency} \\
&+ \beta_7 \left( \texttt{NumberofSeats} == 5 \right) \\
&+ \beta_8 \left( \texttt{NumberofSeats} == 7 \right) \\
&+ \epsilon
\end{align*}
$$

## Results
We can also extract the coefficients from the final model. All coefficients are significant for $\alpha = 0.05$.

```{r, echo=FALSE}
coefficient_tab <- final_model %>%
  summary %$%
  coefficients

coefficient_tab[1:4, ] %>%
  kable
```

## Results 2

```{r, echo=FALSE}
coefficient_tab <- final_model %>%
  summary %$%
  coefficients

coefficient_tab[5:8, ] %>%
  kable
```

## Residuals vs Fitted Values Plot
```{r, echo=FALSE, message=FALSE, warning=FALSE}
std_residuals <- final_model %>%
  rstandard

ggplot(
  mapping = aes(
    x = final_model$fitted.values,
    y = final_model$residuals,
  )
) +
  geom_point(aes(color = std_residuals %>% abs > 2)) +
  geom_smooth(se = F) +
  labs(
    x = "Fitted Values",
    y = "Residuals",
    color = "High Standardized\nResidual\n(absolute value > 2)"
  )
```

## Q-Q Plot
```{r, echo=FALSE}
ggplot(mapping = aes(sample = std_residuals)) +
  geom_qq() +
  geom_qq_line() +
  labs(
    x = "Theorhetical Quantiles",
    y = "Standardized Residuals"
  )
```
## Testing
```{r}
found_ind <- c(5, 7, 9, 12, 18, 22, 28, 29, 35, 36, 42, 44)
found_prices <- c(22585, 35050, 28950, 34995, 48335, 49105, 72175, 73785, 51510, 53010, 54990, 48280)
full_data[found_ind, "PriceinUK"] <- found_prices
test_data <- anti_join(full_data, data, by = "Name") %>%
  select(
    Name,
    PriceinUK,
    Subtitle,
    Acceleration,
    TopSpeed,
    Efficiency,
    NumberofSeats
  ) %>%
  drop_na

log_test <- test_data$PriceinUK %>% log
pred_log_test <- final_model %>% predict(test_data)

log_train <- data$PriceinUK %>% log
pred_log_train <- final_model$fitted.values

ggplot(
  mapping = aes(log_test, pred_log_test)
) +
  geom_abline(slope = 1, intercept = 0) +
  geom_point() +
  labs(
    x = "log(PriceinUK)",
    y = "Predicted log(PriceinUK)"
  )


c(
  (log_test - pred_log_test)^2 %>% mean,
  (test_data$PriceinUK - exp(pred_log_test))^2 %>% mean
)
```
## Conclusion